/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import "RCTRootView.h"
#import "BPush.h"

#define DBNAME    @"aadps.db"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  /**
   * Loading JavaScript code - uncomment the one you want.
   *
   * OPTION 1
   * Load from development server. Start the server from the repository root:
   *
   * $ npm start
   *
   * To run on device, change `localhost` to the IP address of your computer
   * (you can get this by typing `ifconfig` into the terminal and selecting the
   * `inet` value under `en0:`) and make sure your computer and iOS device are
   * on the same Wi-Fi network.
   */

//  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];

  /**
   * OPTION 2
   * Load from pre-bundled file on disk. The static bundle is automatically
   * generated by the "Bundle React Native code and images" build step when
   * running the project on an actual device or running the project on the
   * simulator in the "Release" build configuration.
   */

   jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"aadps"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  // iOS8 下需要使用新的 API
  if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0) {
    UIUserNotificationType myTypes = UIUserNotificationTypeBadge | UIUserNotificationTypeSound | UIUserNotificationTypeAlert;
    
    UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:myTypes categories:nil];
    [[UIApplication sharedApplication] registerUserNotificationSettings:settings];
  }else {
    UIRemoteNotificationType myTypes = UIRemoteNotificationTypeBadge|UIRemoteNotificationTypeAlert|UIRemoteNotificationTypeSound;
    [[UIApplication sharedApplication] registerForRemoteNotificationTypes:myTypes];
  }
  
  [BPush registerChannel:launchOptions apiKey:@"MwbVNFcqWFNq3PRAZIfD6owE" pushMode:BPushModeProduction withFirstAction:nil withSecondAction:nil withCategory:nil useBehaviorTextInput:YES isDebug:NO];
  
  // 禁用地理位置推送 需要再绑定接口前调用。
  
  [BPush disableLbs];
  
  // App 是用户点击推送消息启动
  NSDictionary *userInfo = [launchOptions objectForKey:UIApplicationLaunchOptionsRemoteNotificationKey];
  if (userInfo) {
    [BPush handleNotification:userInfo];
  }
#if TARGET_IPHONE_SIMULATOR
  Byte dt[32] = {0xc6, 0x1e, 0x5a, 0x13, 0x2d, 0x04, 0x83, 0x82, 0x12, 0x4c, 0x26, 0xcd, 0x0c, 0x16, 0xf6, 0x7c, 0x74, 0x78, 0xb3, 0x5f, 0x6b, 0x37, 0x0a, 0x42, 0x4f, 0xe7, 0x97, 0xdc, 0x9f, 0x3a, 0x54, 0x10};
  [self application:application didRegisterForRemoteNotificationsWithDeviceToken:[NSData dataWithBytes:dt length:32]];
#endif
  //角标清0
  [[UIApplication sharedApplication] setApplicationIconBadgeNumber:0];
  return YES;
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
  
  [application registerForRemoteNotifications];
  
  
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  NSLog(@"test:%@",deviceToken);
  [BPush registerDeviceToken:deviceToken];
  [BPush bindChannelWithCompleteHandler:^(id result, NSError *error) {

    // 需要在绑定成功后进行 settag listtag deletetag unbind 操作否则会失败
    
    // 网络错误
    if (error) {
      return ;
    }
    if (result) {
      // 确认绑定成功
      if ([result[@"error_code"]intValue]!=0) {
        return;
      }
      // 获取channel_id
      NSString *myChannel_id = [BPush getChannelId];
      NSLog(@"==%@",myChannel_id);
      NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
      NSString *documents = [paths objectAtIndex:0];
      NSString *database_path = [documents stringByAppendingPathComponent:DBNAME];
      
      if (sqlite3_open([database_path UTF8String], &db) != SQLITE_OK) {
        sqlite3_close(db);
        NSLog(@"数据库打开失败");
      }else{
        NSLog(@"数据库打开成功");
        char *error;
        sqlite3_exec(db, "DELETE FROM options WHERE id = 4", NULL, NULL, &error);
        sqlite3_exec(db, [[NSString stringWithFormat:@"%@%@%@", @"INSERT INTO options VALUES(4, \"", myChannel_id, @"\")"]  cStringUsingEncoding:NSASCIIStringEncoding], NULL, NULL, &error);
        sqlite3_close(db);
      }
    }
  }];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
{


  
  NSLog(@"%@",userInfo);
  
  NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
  NSString *documents = [paths objectAtIndex:0];
  NSString *database_path = [documents stringByAppendingPathComponent:DBNAME];
  
  if (sqlite3_open([database_path UTF8String], &db) != SQLITE_OK) {
    sqlite3_close(db);
    NSLog(@"数据库打开失败");
  }else{
    char *error;
    sqlite3_exec(db, "DELETE FROM options WHERE id = 5", NULL, NULL, &error);
    sqlite3_exec(db, [[NSString stringWithFormat:@"%@%@%@", @"INSERT INTO options VALUES(5, \"", [userInfo objectForKey:@"view"], @"\")"]  cStringUsingEncoding:NSASCIIStringEncoding], NULL, NULL, &error);
    sqlite3_close(db);
  }
}


@end
